FROM wordpress:latest

RUN apt-get -y update && apt-get install -y msmtp msmtp-mta -yqq
RUN curl -sSL https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 -o mhsendmail \
    && chmod +x mhsendmail \
    && mv mhsendmail /usr/local/bin/mhsendmail
